# Generated by Django 4.2 on 2023-04-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name="user's id")),
                ('name', models.CharField(max_length=100, verbose_name="user's name")),
            ],
            options={
                'verbose_name': 'profile',
            },
        ),
    ]
