# Generated by Django 4.2 on 2023-04-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=200)),
                ('text', models.TextField(verbose_name='explanatory text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='receiving time')),
            ],
            options={
                'verbose_name': 'theme',
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
